export const BUSINESS_DEFAULTS = {
  storeName: 'The Point Ko.fi',
  address: 'Set your branch address in Settings',
  contact: 'Set contact number',
  currency: '₱',
  taxRate: 0,
  serviceChargeRate: 0,
  receiptFooter: 'Thank you for your order!'
};

export const SODA_ADDONS = [
  { name: 'Up Size 4oz', price: 10 },
  { name: 'Sea Salt Foam', price: 13 },
  { name: 'Yakult Mist', price: 25 },
  { name: 'Sea Salt Cream Cheese', price: 25 }
];

export const DEFAULT_PRODUCTS = [
  {
    sku: 'DRK-ICED-LATTE',
    name: 'Iced Latte',
    category: 'Drinks',
    subCategory: 'Iced Ko.fi Series',
    size: '16oz',
    basePrice: 75,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'DRK-SPANISH-LATTE',
    name: 'Spanish Latte',
    category: 'Drinks',
    subCategory: 'Iced Ko.fi Series',
    size: '16oz',
    basePrice: 85,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'DRK-CARAMEL-MACCHIATO',
    name: 'Caramel Macchiato',
    category: 'Drinks',
    subCategory: 'Iced Ko.fi Series',
    size: '16oz',
    basePrice: 95,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'DRK-MOCHA-LATTE',
    name: 'Mocha Latte',
    category: 'Drinks',
    subCategory: 'Iced Ko.fi Series',
    size: '16oz',
    basePrice: 95,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'DRK-DIRTY-MATCHA',
    name: 'Dirty Matcha',
    category: 'Drinks',
    subCategory: 'Iced Ko.fi Series',
    size: '16oz',
    basePrice: 95,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'DRK-HAZELNUT-LATTE',
    name: 'Hazelnut Latte',
    category: 'Drinks',
    subCategory: 'Iced Ko.fi Series',
    size: '16oz',
    basePrice: 85,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'DRK-VANILLA-LATTE',
    name: 'Vanilla Latte',
    category: 'Drinks',
    subCategory: 'Iced Ko.fi Series',
    size: '16oz',
    basePrice: 85,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'DRK-AMERICANO',
    name: 'Iced Americano',
    category: 'Drinks',
    subCategory: 'Iced Ko.fi Series',
    size: '16oz',
    basePrice: 65,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'DRK-OREO-PINK-LATTE',
    name: 'Oreo Pink Latte',
    category: 'Drinks',
    subCategory: 'Iced Ko.fi Series',
    size: '16oz',
    basePrice: 99,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'DRK-OREO-LATTE',
    name: 'Oreo Latte',
    category: 'Drinks',
    subCategory: 'Iced Ko.fi Series',
    size: '16oz',
    basePrice: 85,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'NKO-MATCHA-LATTE',
    name: 'Matcha Latte',
    category: 'Drinks',
    subCategory: 'Non-Ko.fi Series',
    size: '16oz',
    basePrice: 95,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'NKO-BERRY-MATCHA',
    name: 'Berry Matcha',
    category: 'Drinks',
    subCategory: 'Non-Ko.fi Series',
    size: '16oz',
    basePrice: 99,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'NKO-OREO-MATCHA',
    name: 'Oreo Matcha',
    category: 'Drinks',
    subCategory: 'Non-Ko.fi Series',
    size: '16oz',
    basePrice: 95,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'NKO-DARK-CHOCOLATE-LATTE',
    name: 'Dark Chocolate Latte',
    category: 'Drinks',
    subCategory: 'Non-Ko.fi Series',
    size: '16oz',
    basePrice: 89,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'NKO-MILKY-STRAWBERRY',
    name: 'Milky Strawberry',
    category: 'Drinks',
    subCategory: 'Non-Ko.fi Series',
    size: '16oz',
    basePrice: 85,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'NKO-MILKY-BLUEBERRY',
    name: 'Milky Blueberry',
    category: 'Drinks',
    subCategory: 'Non-Ko.fi Series',
    size: '16oz',
    basePrice: 85,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  {
    sku: 'NKO-OREO-MILO-BLISS',
    name: 'Oreo Milo Bliss',
    category: 'Drinks',
    subCategory: 'Non-Ko.fi Series',
    size: '16oz',
    basePrice: 95,
    variants: [],
    addOns: [],
    stock: 100,
    trackStock: false,
    active: true
  },
  ...['Green Apple', 'Blueberry', 'Lychee', 'Strawberry', 'Blue Lemonade'].map((name) => ({
    sku: `SODA-${name.toUpperCase().replace(/\s+/g, '-')}`,
    name,
    category: 'Drinks',
    subCategory: 'Soda-Pop Series',
    size: '12oz / 16oz / 22oz',
    basePrice: 25,
    variants: [
      { name: '12oz', price: 25 },
      { name: '16oz', price: 35 },
      { name: '22oz', price: 45 }
    ],
    addOns: SODA_ADDONS,
    stock: 100,
    trackStock: false,
    active: true
  })),
  {
    sku: 'WS-TUNA',
    name: 'Tuna WS',
    category: 'Snacks',
    subCategory: 'Waffle Sandwich Series',
    basePrice: 65,
    variants: [],
    addOns: [],
    stock: 30,
    trackStock: true,
    active: true,
    notes: 'Includes Garlic Mayo and Cheese Sauce.'
  },
  {
    sku: 'WS-BURGER',
    name: 'Burger WS',
    category: 'Snacks',
    subCategory: 'Waffle Sandwich Series',
    basePrice: 55,
    variants: [],
    addOns: [],
    stock: 30,
    trackStock: true,
    active: true,
    notes: 'Includes Garlic Mayo and Cheese Sauce.'
  },
  {
    sku: 'WS-EGG',
    name: 'Egg WS',
    category: 'Snacks',
    subCategory: 'Waffle Sandwich Series',
    basePrice: 50,
    variants: [],
    addOns: [],
    stock: 30,
    trackStock: true,
    active: true,
    notes: 'Includes Garlic Mayo and Cheese Sauce.'
  },
  {
    sku: 'WS-HAM',
    name: 'Ham WS',
    category: 'Snacks',
    subCategory: 'Waffle Sandwich Series',
    basePrice: 50,
    variants: [],
    addOns: [],
    stock: 30,
    trackStock: true,
    active: true,
    notes: 'Includes Garlic Mayo and Cheese Sauce.'
  },
  {
    sku: 'SNK-FRIES-OVERLOAD',
    name: 'Fries Overload',
    category: 'Snacks',
    subCategory: 'Overload Snack',
    basePrice: 120,
    variants: [],
    addOns: [],
    stock: 40,
    trackStock: true,
    active: true
  },
  {
    sku: 'SNK-NATCHOS-OVERLOAD',
    name: 'Natchos Overload',
    category: 'Snacks',
    subCategory: 'Overload Snack',
    basePrice: 100,
    variants: [],
    addOns: [],
    stock: 40,
    trackStock: true,
    active: true
  },
  {
    sku: 'FN-PLAIN',
    name: 'FN (Plain)',
    category: 'Snacks',
    subCategory: 'Fried Noodles - Cabbage Base',
    basePrice: 50,
    variants: [],
    addOns: [],
    stock: 50,
    trackStock: true,
    active: true
  },
  {
    sku: 'FN-EGG',
    name: 'FN w/ Egg',
    category: 'Snacks',
    subCategory: 'Fried Noodles - Cabbage Base',
    basePrice: 65,
    variants: [],
    addOns: [],
    stock: 50,
    trackStock: true,
    active: true
  },
  {
    sku: 'FN-SIOPAO',
    name: 'FN w/ Siopao',
    category: 'Snacks',
    subCategory: 'Fried Noodles - Cabbage Base',
    basePrice: 70,
    variants: [],
    addOns: [],
    stock: 50,
    trackStock: true,
    active: true
  },
  {
    sku: 'FN-HAM',
    name: 'FN w/ Ham',
    category: 'Snacks',
    subCategory: 'Fried Noodles - Cabbage Base',
    basePrice: 65,
    variants: [],
    addOns: [],
    stock: 50,
    trackStock: true,
    active: true
  },
  {
    sku: 'FN-BURGER-PATTY',
    name: 'FN w/ Burger Patty',
    category: 'Snacks',
    subCategory: 'Fried Noodles - Cabbage Base',
    basePrice: 65,
    variants: [],
    addOns: [],
    stock: 50,
    trackStock: true,
    active: true
  },
  {
    sku: 'FN-SIOMAI',
    name: 'FN w/ Siomai',
    category: 'Snacks',
    subCategory: 'Fried Noodles - Cabbage Base',
    basePrice: 65,
    variants: [],
    addOns: [],
    stock: 50,
    trackStock: true,
    active: true
  },
  {
    sku: 'SAMYANG-BULDAK-CARBONARA',
    name: 'Samyang Buldak Carbonara',
    category: 'Snacks',
    subCategory: 'Samyang Buldak',
    basePrice: 0,
    variants: [],
    addOns: [],
    stock: 20,
    trackStock: true,
    active: false,
    notes: 'No visible price in the reference photo. Set price and activate in Inventory.'
  }
];
